/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/indexstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/pages/alstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/alstyle`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/azurlane` | `/azurlane`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/indexstyle`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/pages/alstyle`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/screens/alstyle`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/azurlane` | `/azurlane`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../styles/indexstyle${`?${string}` | `#${string}` | ''}` | `/../styles/pages/alstyle${`?${string}` | `#${string}` | ''}` | `/../styles/screens/alstyle${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/azurlane${`?${string}` | `#${string}` | ''}` | `/azurlane${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/homepage${`?${string}` | `#${string}` | ''}` | `/homepage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/indexstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/pages/alstyle`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/alstyle`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/azurlane` | `/azurlane`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownInputParams; };
    }
  }
}
