/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/gistyle`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/hi3style`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/updstyle`; params?: Router.UnknownInputParams; } | { pathname: `/components/gamebar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/honkaistarrail` | `/honkaistarrail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bluearchive` | `/bluearchive`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/arknights` | `/arknights`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/azurlane` | `/azurlane`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/genshinimpact` | `/genshinimpact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/honkaiimpact3` | `/honkaiimpact3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/umamusumeprettyderby` | `/umamusumeprettyderby`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/screens/gistyle`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/screens/hi3style`; params?: Router.UnknownOutputParams; } | { pathname: `/../styles/screens/updstyle`; params?: Router.UnknownOutputParams; } | { pathname: `/components/gamebar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/honkaistarrail` | `/honkaistarrail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bluearchive` | `/bluearchive`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/arknights` | `/arknights`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/azurlane` | `/azurlane`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/genshinimpact` | `/genshinimpact`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/honkaiimpact3` | `/honkaiimpact3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/umamusumeprettyderby` | `/umamusumeprettyderby`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../styles/screens/gistyle${`?${string}` | `#${string}` | ''}` | `/../styles/screens/hi3style${`?${string}` | `#${string}` | ''}` | `/../styles/screens/updstyle${`?${string}` | `#${string}` | ''}` | `/components/gamebar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/honkaistarrail${`?${string}` | `#${string}` | ''}` | `/honkaistarrail${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bluearchive${`?${string}` | `#${string}` | ''}` | `/bluearchive${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/arknights${`?${string}` | `#${string}` | ''}` | `/arknights${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/azurlane${`?${string}` | `#${string}` | ''}` | `/azurlane${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/genshinimpact${`?${string}` | `#${string}` | ''}` | `/genshinimpact${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/homepage${`?${string}` | `#${string}` | ''}` | `/homepage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/honkaiimpact3${`?${string}` | `#${string}` | ''}` | `/honkaiimpact3${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/umamusumeprettyderby${`?${string}` | `#${string}` | ''}` | `/umamusumeprettyderby${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/gistyle`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/hi3style`; params?: Router.UnknownInputParams; } | { pathname: `/../styles/screens/updstyle`; params?: Router.UnknownInputParams; } | { pathname: `/components/gamebar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/honkaistarrail` | `/honkaistarrail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bluearchive` | `/bluearchive`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/arknights` | `/arknights`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/azurlane` | `/azurlane`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/genshinimpact` | `/genshinimpact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/honkaiimpact3` | `/honkaiimpact3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/umamusumeprettyderby` | `/umamusumeprettyderby`; params?: Router.UnknownInputParams; };
    }
  }
}
